server:
  port: 8888
spring:
  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer